name: Hello World Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allows manual run

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello Message
        run: echo "ğŸ‘‹ Hello from GitHub Actions!"

      - name: Print Hello Message2
        run: echo "ğŸ‘‹ Hello Anupama"  

      - name: Print Custom Message
        run: |
         echo "ğŸ‘‹ Hello ${{ github.actor }}! Welcome to GitHub Actions."
         echo "ğŸ“ Commit message: ${{ github.event.head_commit.message }}"
         echo "ğŸ’¡ Branch name: ${{ github.ref_name }}"
         echo "ğŸ“ Repository: ${{ github.repository }}"
         echo "ğŸ§‘ Committer: ${{ github.actor }}"
      - name: Show all environment variables
        run: printenv | sort
